name: Build Launcher EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Langkah otomatis untuk menyiapkan lingkungan compiler MSVC C++ tanpa perlu path manual
    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile EXE
      shell: cmd
      run: |
        cl.exe /O2 /MT main.cpp /link user32.lib shell32.lib /SUBSYSTEM:WINDOWS /OUT:PeluncurAplikasi.exe

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Peluncur-EXE-Selesai
        path: PeluncurAplikasi.exe
        
